### ISSUE TITLE
[Suggestion] Per world configuration or toggle

### ISSUE THREAD

**Issue by Jadiction** [drtshock/Factions#1251]
### Idea
Configurations per world or a way to disable/enable this plugin per world.

### Details
The ability for "per world compatibility". A lot (perhaps even most) servers use multiple worlds. Having the option to have factions on one world would be very ideal. A different configuration per-world would be a neat option but seems a bit much. I'd be happy with a toggle per world. For example:

```Enabled on worlds:
  world: false
  spawn: false
  factionWorld: true
```

**Comment by timriker** [comment]
In luckperms I enable some commands only in the factions (grief) world. For example, I enable the vault access only in the grief world:
```
- factions.vault:
    value: true
    world: grief
- factions.vault:
    value: true
    world: grief_nether
 - factions.vault:
    value: true
    world: grief_the_end
 - playervaults.amount.2:
    value: true
    world: grief
 - playervaults.amount.2:
    value: true
    world: grief_nether
 - playervaults.amount.2:
    value: true
    world: grief_the_end`
```
Allowing vault access from a creative world is a Bad Idea. :)

It would be nice in my setup to have factions enabled in all the grief* worlds, and disabled elsewhere.

It would be awesome to have different worlds with different configs, but that's likely a lot of work.
