### ISSUE TITLE
Map update issue

### ISSUE THREAD

**Issue by MrTrinax** [drtshock/Factions#1260]
### FactionsUUID Version
*v1.6.9.5-u0.4.0-b150*

### Server Version
*Paper version git-Paper-157 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)*

### Logs
*Log is not necessary for this issue*

### Details
*When using "/f map on", it doesn't always update adjacent chunks. Often the map will skip updating/loading any adjacent chunks and update when entering the second chunk.
Video of the issue: https://www.youtube.com/watch?v=nnjLjApd4tk&feature=youtu.be*

**Comment by CmdrKittens** [comment]
In `config.yml` is the following:

```yaml
findfactionsexploit:
  cooldown: 2000 # in milliseconds. 2000 = 2 seconds.
  log: false
```

Can you try setting the cooldown to something lower like 1000, and log to true, and see what happens?
